### ISSUE TITLE
SST Token Design

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-gift#3]
群众路线是党的根本工作路线，以毛泽东为主要代表的中国共产党在长期斗争中形成了一切为了群众，一切依靠群众和从群众中来，到群众中去的群众路线。群众路线是毛泽东思想三个活的灵魂之一，是党的生命线和根本工作路线。坚持党的群众路线，是党在长期革命和建设中制胜的法宝，要在新形势下发扬光大。要带领群众发展致富，把解决好群众的利益问题作为坚持群众路线的重要内容，维护好群众的合法利益。

In order to make 群众路线 possible, we need to issue SST token before we implement the dapp, we need to test our dapp in mainnet, and reward some of our token to our early adopter. (I'd like to call this, ITO or initial test offer)

We could use the same token design as CMU to issue SST token, and transfer a part of the global fee into SST to award early adopter.

**Comment by flyq** [comment]
of course!
>and transfer a part of the global fee into SST to award early adopter.
it is automated or handmade？

**Comment by lychees** [comment]
> it is automated or handmade？
Automated. Use the powh algorithm which we use in CTN && CMU.

**Comment by flyq** [comment]
get it

**Comment by flyq** [comment]
#6
